version: 2.1

orbs:
  kaocha: lambdaisland/kaocha@0.0.2
  clojure: lambdaisland/clojure@0.0.6

commands:
  checkout_and_run:
    parameters:
      clojure_args:
        type: string
      clojure_version:
        type: string
    steps:
      - checkout
      - run: npm install ws
      - clojure/with_cache:
          cache_version: << parameters.clojure_version >>
          steps:
            - kaocha/execute:
                args: "--reporter documentation --plugin cloverage --codecov"
                clojure-args: << parameters.clojure_args >>
                clojure_version: << parameters.clojure_version >>
                aliases: ":dev:test:test-check:cljs:instaparse:malli"
            - kaocha/upload_codecov
            - store_artifacts:
                path: /tmp/gc-log.txt

jobs:
  java-16-clojure-1_10:
    executor: clojure/openjdk16
    steps: [{checkout_and_run: {clojure_version: "1.10.2", clojure_args: "-J-XX:+UseSerialGC -J-Xmx2g -J-Xlog:gc*:file=/tmp/gc-log.txt"}}]
  java-16-clojure-1_9:
    executor: clojure/openjdk16
    steps: [{checkout_and_run: {clojure_version: "1.9.0", clojure_args: "-J-XX:+UseSerialGC -J-Xmx2g -J-Xlog:gc*:file=/tmp/gc-log.txt"}}]
  java-15-clojure-1_10:
    executor: clojure/openjdk15
    steps: [{checkout_and_run: {clojure_version: "1.10.2", clojure_args: "-J-XX:+UseSerialGC -J-Xmx2g -J-Xlog:gc*:file=/tmp/gc-log.txt"}}]

  java-15-clojure-1_9:
    executor: clojure/openjdk15
    steps: [{checkout_and_run: {clojure_version: "1.9.0", clojure_args: "-J-XX:+UseSerialGC -J-Xmx2g -J-Xlog:gc*:file=/tmp/gc-log.txt"}}]
    
  java-11-clojure-1_10:
    executor: clojure/openjdk11
    steps: [{checkout_and_run: {clojure_version: "1.10.2", clojure_args: "-J-XX:+UseSerialGC -J-Xmx2g -J-Xlog:gc*:file=/tmp/gc-log.txt"}}]

  java-11-clojure-1_9:
    executor: clojure/openjdk11
    steps: [{checkout_and_run: {clojure_version: "1.9.0", clojure_args: "-J-XX:+UseSerialGC -J-Xmx2g -J-Xlog:gc*:file=/tmp/gc-log.txt"}}]

workflows:
  kaocha_test:
    jobs:
      - java-16-clojure-1_10
      - java-16-clojure-1_9
      - java-15-clojure-1_10
      - java-15-clojure-1_9
      - java-11-clojure-1_10
      - java-11-clojure-1_9
